#!/usr/bin/env bash

clean=false
message=''
branch=''

while getopts 'm:' flag; do
    case "${flag}" in
        m) message="${OPTARG}" ;;
    esac
done

git fetch
git switch -C master

# Sync home directory
rsync -avz --delete\
    $HOME/{bin,.zshrc,.p10k.zsh} \
    $HOME/repositories/github.com/nssteinbrenner/dotfiles

# Sync .config
rsync -avz --delete \
    $HOME/.config/{mako,nvim,fontconfig,foot,fuzzel,fzf,sway,tmux,tmux-sessionizer,waybar} \
    $HOME/repositories/github.com/nssteinbrenner/dotfiles/.config

git add -A

if [[ -z $message ]]; then
    message="Update dotfiles"
fi

git commit -m "$(date +%F) - ${message}"
git push
