#!/usr/bin/env bash

clean=false
message=''

while getopts 'm:' flag; do
    case "${flag}" in
        m) message="${OPTARG}" ;;
    esac
done

git fetch
git switch -C master

rsync -avz --delete\
    $HOME/{.zshrc,.p10k.zsh,.gruvbox_p10k.zsh} \
    $HOME/repositories/github.com/nssteinbrenner/dotfiles

rsync -avz --delete \
    $HOME/.config/{mako,nvim,fontconfig,foot,fuzzel,fzf,sway,tmux,tmux-sessionizer,waybar} \
    $HOME/repositories/github.com/nssteinbrenner/dotfiles/.config

rsync -avz --delete\
    $HOME/.local/bin/ \
    $HOME/repositories/github.com/nssteinbrenner/dotfiles/.local

git add -A

if [[ -z $message ]]; then
    message="Update dotfiles"
fi

git commit -m "$(date +%F) - ${message}"
git push
